### ISSUE TITLE
Can't resolve 'react-addons-css-transition-group'

### ISSUE THREAD

**Issue by prasid444** [edwardfhsiao/react-picky-date-time#10]
I added this library through `yarn add react-picky-date-time` and used copied the same code as that of the first example. But its not running

`ModuleNotFoundError: Module not found: Error: Can't resolve 'react-addons-css-transition-group' in '/Users/prasid444/Desktop/own/mcqhall-frontend-next/node_modules/react-picky-date-time/lib/components/Calendar'
    at /Users/prasid444/Desktop/own/mcqhall-frontend-next/node_modules/webpack/lib/Compilation.js:925:10
    at /Users/prasid444/Desktop/own/mcqhall-frontend-next/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /Users/prasid444/Desktop/own/mcqhall-frontend-next/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /Users/prasid444/Desktop/own/mcqhall-frontend-next/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /Users/prasid444/Desktop/own/mcqhall-frontend-next/node_modules/neo-async/async.js:2830:7
    at /Users/prasid444/Desktop/own/mcqhall-frontend-next/node_modules/neo-async/async.js:6877:13
    at /Users/prasid444/Desktop/own/mcqhall-frontend-next/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /Users/prasid444/Desktop/own/mcqhall-frontend-next/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /Users/prasid444/Desktop/own/mcqhall-frontend-next/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/prasid444/Desktop/own/mcqhall-frontend-next/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/prasid444/Desktop/own/mcqhall-frontend-next/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /Users/prasid444/Desktop/own/mcqhall-frontend-next/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/prasid444/Desktop/own/mcqhall-frontend-next/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/prasid444/Desktop/own/mcqhall-frontend-next/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/prasid444/Desktop/own/mcqhall-frontend-next/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/prasid444/Desktop/own/mcqhall-frontend-next/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43`

Also after manually adding  `  react-picky-date-time`  and ` react-addons-update`, It gives error as shown in the image below
<img width="1280" alt="Screen Shot 2020-06-11 at 11 19 25 AM" src="https://user-images.githubusercontent.com/19533229/84349794-cdf62380-abd7-11ea-9e3d-da5cf6c05781.png">

**Comment by edwardfhsiao** [comment]
Hi, @prasid444  which version are you using? I recommend installing the package via NPM

https://codesandbox.io/s/lucid-breeze-9uxfq?file=/package.json works fine.

**Comment by prasid444** [comment]
I was using `1.6.1`

**Comment by prasid444** [comment]
`   "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-addons-css-transition-group": "15.6.2",
    "react-addons-update": "15.6.2",
    "react-picky-date-time": "1.6.0" `

<img width="1280" alt="Screen Shot 2020-06-11 at 1 48 37 PM" src="https://user-images.githubusercontent.com/19533229/84360758-554c9280-abea-11ea-8b2f-b9d1535a8a22.png">

**Comment by edwardfhsiao** [comment]
can you create a repo for me to debug?

**Comment by prasid444** [comment]
Sure give me some time
