### ISSUE TITLE
Error on fresh install

### ISSUE THREAD

**Issue by atompie** [edwardfhsiao/react-picky-date-time#11]
./node_modules/react-picky-date-time/lib/components/Calendar/index.js
Module not found: Can't resolve 'react-addons-css-transition-group' in '/home/risto/WebstormProjects/react.uql-client/node_modules/react-picky-date-time/lib/components/Calendar'

**Comment by edwardfhsiao** [comment]
@atompie Hi, ```react-addons-css-transition-group``` is one of the dependency, try install it manually by
```npm i react-addons-css-transition-group --save```

**Comment by atompie** [comment]
Ok, I did it. But should not it be resolved automatically?

**Comment by edwardfhsiao** [comment]
I declared it in```peerDependencies```, not sure how to make it automatically. Besides, should it? That is debatable.
