### ISSUE TITLE
手机页面中，顶部的年月选择不起作用

### ISSUE THREAD

**Issue by fanyeb** [edwardfhsiao/react-picky-date-time#3]
请问下，年月选择那边点击打开后，一点击某个月或某年，会自动收起，pc页面没问题，手机页面就不行。
这个问题怎么解决呢，谢谢。

**Comment by fanyeb** [comment]
![qq 20190116111111](https://user-images.githubusercontent.com/34863987/51224109-74a4a900-197f-11e9-9241-2bff54a8f705.png)

**Comment by edwardfhsiao** [comment]
我都没发现呢，我看看

**Comment by edwardfhsiao** [comment]
@fanyeb try v1.2.7

**Comment by fanyeb** [comment]
谢谢，已经可以了
