### ISSUE TITLE
Can you Add Spanish locale por favor

### ISSUE THREAD

**Issue by beersnob55855** [edwardfhsiao/react-picky-date-time#5]
var LOCALE_RANGE = ['en-us', 'zh-cn', 'es', 'en'];

var DEFAULT_LACALE = 'en-us';

var DEFAULT_SIZE = 'm';

var LANG = {
  'en-us': {
    today: 'Today',
    reset: 'Reset',
    'reset-date': 'Reset Date',
    clear: 'Clear',
    now: 'Now'
  },
  'en': {
    today: 'Today',
    reset: 'Reset',
    'reset-date': 'Reset Date',
    clear: 'Clear',
    now: 'Now'
  },
  'es': {
    today: 'Hoy',
    reset: 'Reiniciar',
    'reset-date': 'Reiniciar Fecha',
    clear: 'Borrar',
    now: 'Ahora'
  },
  'zh-cn': {
    today: '今天',
    reset: '重置',
    'reset-date': '重置日期',
    clear: '清零',
    now: '现在'
  }
};

// CALENDAR

var PREV_TRANSITION = 'prev';
var NEXT_TRANSITION = 'next';

var SELECTOR_YEAR_SET_NUMBER = 5;

var WEEK_NAME = {
  'en-us': ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  'en': ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  'zh-cn': ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
  'es': ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb']
};

var MONTH_NAME = {
  'en-us': ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
  'en': ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
  'zh-cn': ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
  'es': ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']
};

**Comment by edwardfhsiao** [comment]
Hi @beersnob55855 ,
Please check v1.3.1. Now you can provide your own locale by following the rules in -> https://github.com/edwardfhsiao/react-picky-date-time#custom-locale.

example: https://codesandbox.io/s/l3n2ypvrzl
